package com.tlo.specialist.util;

import com.tlo.specialist.util.impl.IBMCompanyContactInfoParser;
import com.tlo.specialist.util.impl.SimpleCompanyContactInfoParser;

public class CompanyContactInfoParserFactory {
	
	public static final String[] SIMPLE_COMPANY_CONTACT_PARSER_LINKS = {
		"www.oracle.com",
		"www.accenture.com",
		"www.google.com",
		"www2.deloitte.com",
		"www.cognizant.com",
		"www.unilever.com",
		"www.schneider-electric.com",
		"www.xerox.com",
		"atos.net",
		"www.bayer.com",
		"www.airbus.com",
		"www.larsentoubro.com",
		"www.goldmansachs.com",
		"www.bakerhughes.com",
		"www.basf.com",
		"about.nike.com",
		"www.eaton.com",
		"www.fluor.com",
		"www.convergys.com",
		"www.standardbank.com",
		"www.dupont.com",
		"www.bnymellon.com",
		"www.edwardjones.com",
		"www.weatherford.com",
		"www.statestreet.com",
		"www.ihgplc.com",
		"www.aflac.com",
		"www.fisglobal.com",
		"www.mckinsey.com",
		"www.technipfmc.com",
		"www.willis.co.uk",
		"www.cerner.com",
		"www.bhpbilliton.com",
		"about.hyatt.com",
		"www.gao.gov",
		"www.mckesson.com",
		"www.adidas-group.com",
		"www.inditex.com",
		"www.fiserv.com",
		"www.gapinc.com",
		"pearson.com",
		"www.marykay.com",
		"www.st.com",
		"www.riotinto.com",
		"www.syntelinc.com",
		"www.t-systems.com",
		"www.symantec.com",
		"www.adobe.com",
		"www.teksystems.com",
		"www.emerson.com",
		"www.dimensiondata.com",
		"www.nbcuniversal.com",
		"www.tata.com",
		"www.wsp-pb.com",
		"www.tatasteel.com",
		"www.magna.com",
		"www.caci.com",
		"www.utoronto.ca",
		"www.snclavalin.com",
		"www.blackrock.com",
		"www.marsh.com",
		"www.iocl.com",
		"www.tetrapak.com",
		"www.mountsinaihealth.org",
		"www.odebrecht.com",
		"www.suncor.com",
		"www.pitneybowes.com",
		"www.bswhealth.com",
		"www.aricent.com",
		"www.infor.com",
		"www.embraer.com",
		"www.westrock.com",
		"www.dallasisd.org",
		"www.longandfoster.com",
		"www2.chubb.com",
		"www.sysco.com",
		"www.broadcom.com",
		"www.insidesecure.com",
		"www.zte.com",
		"www.exlservice.com",
		"www.ab-inbev.com",
		"www.parsons.com",
		"havas.com",
		"www.exeloncorp.com",
		"www.tieto.com",
		"company.ingersollrand.com",
		"www.chrobinson.com",
		"www.citrix.com",
		"www.ef.com",
		"www.infineon.com",
		"www.covance.com",
		"www.teletech.com",
		"www.aegon.com",
		"www.kone.us",
		"www.zimmerbiomet.com",
		"www.hopkinsmedicine.org",
		"www.tenethealth.com",
		"www.globalfoundries.com",
		"www.jti.com",
		"www.unimelb.edu.au",
		"www.inventivhealth.com",
		"www.airindia.in",
		"www.beaumont.org",
		"www.richemont.com",
		"www.mylan.com",
		"www.flsmidth.com",
		"wexnermedical.osu.edu",
		"www.west.com",
		"gdmissionsystems.com",
		"www.amtrakoig.gov",
		"www.lyondellbasell.com",
		"www.pernod-ricard-usa.com",
		"www.essar.com",
		"ats.avnet.com",
		"locations.geisinger.org",
		"www.gegridsolutions.com",
		"www.brighthorizons.com",
		"www.ferrero.com",
		"www.levistrauss.com",
		"www2.dpsk12.org",
		"www.celestica.com",
		"www.merckmillipore.com",
		"www.alfalaval.com",
		"www.nationwidechildrens.org",
		"www.leonardocompany.com",
		"www.schindler.com",
		"www.j-sainsbury.co.uk",
		"www.greystar.com",
		"www.textron.com",
		"www.carefusion.com",
		"www.ferrovial.com",
		"www.vfc.com",
		"www.fbi.gov",
		"www.trinity-health.org",
		"www.orbitalatk.com",
		"www.alibabagroup.com",
		"www.parklandhospital.com",
		"www.omnicare.com",
		"www.fultonschools.org",
		"www.jacksonhealth.org",
		"www.fortbendisd.com",
		"coniferhealth.com",
		"www.steward.org",
		"www.bjc.org",
		"www.stanleysecuritysolutions.com",
		"www.meridianhealth.com",
		"www.leehealth.org",
		"www.crown.com",
		"www.palmettohealth.org",
		"www.fsresidential.com",
		"www.emersonclimate.com",
		"www.bluescope.com",
		"www.apollo.edu",
		"www.mccain.com",
		"www.boston.gov",
		"www.l3t.com",
		"novelis.com",
		"www.tdcj.state.tx.us",
		"www.whitbread.co.uk",
		"www.massmutual.com",
		"mlb.mlb.com",
		"www.welspun.com",
		"www.ladbrokescoralplc.com",
		"www.valeant.com",
		"www.nabors.com",
		"www.pccw.com",
		"www.ul.com",
		"www.methodisthealth.org",
		"www2.emerson.com",
		"www.ineos.com",
		"www.pnkinc.com",
		"www.dayzim.com",
		"www.omnicomgroup.com",
		"www.gelighting.com",
		"www.willistowerswatson.com",
		"www.estes-express.com",
		"www.ametek.com",
		"www.primehealthcare.com",
		"www.aegworldwide.com",
		"www.pactiv.com",
		"www.bamco.com",
		"www.anthem.com",
		"www.autogrill.com",
		"www.brockgroup.com",
		"www.ohsu.edu",
		"ableserve.com",
		"www.alphanr.com",
		"www.sourcehov.com",
		"abc.go.com",
		"www.brookfieldproperties.com",
		"www.qualfon.com",
		"www.elbitsystems-us.com",
		"www.iacgroup.com",
		"www.bell-labs.com",
		"www.andrewsinternational.com",
		"associaonline.com",
		"www.cincinnatistate.edu",
		"www.forestriverinc.com",
		"www.murata.com",
		"www.kubota-kma.com",
		"www.nyp.org",
		"www.aphp.fr",
		"www.amd.com",
		"www.ubc.ca",
		"www.relx.com",
		"www.chinasofti.com",
		"www.ecintl.com",
		"www.osigroup.com",
		"loews.com",
		"www.hcpnv.com",
		"www.theservicecompanies.com",
		"www.cnrs.fr",
		"www.uwv.nl",
		"www.pwc.com"
	};
	
	public static final String[] IBM_COMPANY_CONTACT_PARSER_LINKS = {
		"www.ibm.com"
	};

	public static CompanyContactInfoParser getParser(String websiteLink) {
		if (isLinkIncluded(websiteLink, SIMPLE_COMPANY_CONTACT_PARSER_LINKS)) {
			return new SimpleCompanyContactInfoParser();
		} else if (isLinkIncluded(websiteLink, IBM_COMPANY_CONTACT_PARSER_LINKS)) {
			return new IBMCompanyContactInfoParser();
		}
		return null;
	}
	
	static boolean isLinkIncluded(String link, String[] includedLinks) {
		for (String includedLink : includedLinks) {
			if (link.contains(includedLink)) {
				return true;
			} else {
				continue;
			}
		}
		return false;
	}
}
